// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://bibsduqgpmeuwbsgdoih.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpYnNkdXFncG1ldXdic2dkb2loIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMwNjc4NDIsImV4cCI6MjA3ODY0Mzg0Mn0.4_RC9CpyoJ033EmVB-p8Fb5DTOlya1qFOiG-OFCyAw4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);